spring:
  application:
    name: bank-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_system}
    username: ${DB_USERNAME:hristiyanivanov}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080

bank:
  seed:
    enabled: true
